general:
  res_folder : '/mnt/ernie_main/Ghassan/ephys/data'
  h5filename : 'stim_resp_bipole.hdf5' #general hdf5 name that should hold for most runs
  logdir : 'logs/'
agg:
  sig_test : true
  peak_times: 
    n_peaks: 1
plot:
  gen_plots : true
  plot_path : "/mnt/ernie_main/Ghassan/ephys/data/SUBJ/fig/"
  sig_test : true
  artifact_test : false
  max_entry : 50
  plot_types : ['reparam-agg','cross', 'raw']