peri_para:
  stats : 'none'
  num_cores : 20
  buffer : 60
  verbose : False
ei_bal:
  num_cores : 24
power:
  num_cores: 24
  bands : ['delta', 'beta']
plt_flow_power:
  num_cores: 4
  band: "beta"
  conn_band : "all" #possible bands: 'alpha', 'beta', 'theta', 'gamma_l', 'gamma_H'
  pipeline: zscore_merge #plot #zscore_merge # plot #"zscore_merge" #plot # 
  merged_fname : 'all_merged_HI3_centered_pow_freq.csv'
  involvement : 'instantaneous'
  plot_type : 'lineplot'
  anatomical : False
  norm_szrs: False
  summarize : True
  group_cols : ['patID',  'win_sz_st_end','ever_involved', 'region_involved', 'source', 'target','freq_band' ]
  numeric_cols: ['value', 'z_pdc', 'z_beta']
  threshold : 3
  plot_kwargs:
    levels : 5
    alpha : 0.4
    fill : True
    y : 'z_beta'
    x : 'win_sz_st_end'
    plot_stats : True
    hue : "ever_involved"
  sz_types : []
  title : 'Directed  Connectivity vs. Delta  Power'
  relationships : [["nz_nz_True", "nz_soz_True", ],
                   ["nz_nz_False", "nz_soz_False"],
                  ]
  subsample : 1 #2000
  random_state : 69420
  pre_merged : True
pipeline: 'power'
#relationships : [["nz_nz_True", "nz_nz_False", "nz_soz_True", "nz_soz_False"],
#                   ["nz_pz_True", "nz_pz_False"],
#                   ["soz_soz_True", "soz_soz_False", "soz_nz_True", "soz_nz_False"]
#                  ]