peri_para:
  stats : 'full' # set if you wantt to z_score connectivity None will default to no zscore
  num_cores : 12
  buffer : 60
  verbose : True
  pipeline: 'classify_agg'
  conn : ['in_conn', 'net_conn']
  overwrite : True
  out_path : '../data/classify_dense_peri_only_inout/'
  windows : 'dense'
  dense_lw_lim : -10
  dense_up_lim : 20
  zscore: True
  n_jobs : 20
  filt_engel1 : 'Full'
  engel_subj : 'subj_list_engel1.csv'

ei_bal:
  num_cores : 24
power:
  num_cores: 24
  bands : ['delta', 'beta']
plt_flow_power:
  num_cores: 1
  band: "beta"
  conn_band : "all" #possible bands: 'alpha', 'beta', 'theta', 'gamma_l', 'gamma_H'
  pipeline: "plot" #'stats' #'plot' #"score_bips" #"merge" #plot #zscore_merge # plot #"zscore_merge" #plot # 
  merged_fname : "merged_flow_pow_subsampFull_5win.csv" #'all_merged_HI3_54_centered_pow_freq.csv' #score_merged_anat.csv #'all_merged_z_flow_centered_pow_freq.csv'
  involvement : 'summary'
  plot_type : 'corr'
  anatomical : False
  norm_szrs: False
  summarize : True
  group_cols : ['patID',  'win_sz_st_end','ever_involved', 'region_involved', 'source', 'target','freq_band' ]
  numeric_cols: ['value',  'z_beta']
  threshold : 2
  plot_kwargs:
    levels : 5
    alpha : 0.4
    fill : True
    y : 'value'
    x : 'z_beta'
    conn_val : 'value'
    plot_stats : True
   # hue : "region_involved"
  sz_types : []
  title : 'Directed  Connectivity vs. Delta  Power'
  relationships : [["nz_nz_True", "nz_soz_True", ],
                   ["nz_nz_False", "nz_soz_False"],
                  ]
  subsample : 3000
  random_state : 69420
  pre_merged : True
pipeline: 'power'
#relationships : [["nz_nz_True", "nz_nz_False", "nz_soz_True", "nz_soz_False"],
#                   ["nz_pz_True", "nz_pz_False"],
#                   ["soz_soz_True", "soz_soz_False", "soz_nz_True", "soz_nz_False"]
#                  ]