peri_para:
  stats : 'none'
  num_cores : 20
  buffer : 60
  verbose : False
ei_bal:
  num_cores : 24
power:
  num_cores: 24
  bands : ['delta', 'beta']
plt_flow_power:
  num_cores: 6
  band: "beta"
  conn_band : "alpha" #possible bands: 'alpha', 'beta', 'theta', 'gamma_l', 'gamma_H'
  pipeline: "stats"
  merged_fname : ../data/merged_flow_pow_subsampFull_anat.csv
  plot_type : 'joint_kde'
  anatomical : False
  norm_szrs: True
  plot_kwargs:
    levels : 5
    alpha : 0.4
    fill : True
    y : 'value'
    x : 'z_beta'
  sz_types : []
  title : 'Directed  Connectivity vs. Delta  Power'
  relationships : [["nz_nz_True", "nz_soz_True", ],
                   ["nz_nz_False", "nz_soz_False"],
                  ]
  subsample : 5000
  random_state : 69420
  pre_merged : True
pipeline: 'power'
#relationships : [["nz_nz_True", "nz_nz_False", "nz_soz_True", "nz_soz_False"],
#                   ["nz_pz_True", "nz_pz_False"],
#                   ["soz_soz_True", "soz_soz_False", "soz_nz_True", "soz_nz_False"]
#                  ]