#!/bin/bash
python resultAggregator.py -s 'Epat27' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat27'
python resultAggregator.py -s 'Epat26' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat26'
python resultAggregator.py -s 'Epat30' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat30'
python resultAggregator.py -s 'Epat31' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat31'
python resultAggregator.py -s 'Epat35' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat35'
python resultAggregator.py -s 'Epat37' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat37'
python resultAggregator.py -s 'Epat38' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat38'
##python resultAggregator.py -s 'Epat39' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat39'
python resultAggregator.py -s 'Epat43' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat43'
python resultAggregator.py -s 'Spat30' -p '/mnt/ernie_main/Ghassan/ephys/data/Spat30'
##python resultAggregator.py -s 'Spat31' -p '/mnt/ernie_main/Ghassan/ephys/data/Epat31'
##python resultAggregator.py -s 'Spat34' -p '/mnt/ernie_main/Ghassan/ephys/data/Spat34'
python resultAggregator.py -s 'Spat36' -p '/mnt/ernie_main/Ghassan/ephys/data/Spat36'
python resultAggregator.py -s 'Spat37' -p '/mnt/ernie_main/Ghassan/ephys/data/Spat37'
##python resultAggregator.py -s 'Spat52' -p '/mnt/ernie_main/Ghassan/ephys/data/Spat52'