peri_para:
  stats : 'none'
  num_cores : 20
  buffer : 60
  verbose : False
ei_bal:
  num_cores : 24
power:
  num_cores: 24
  bands : ['delta', 'beta']
plt_flow_power:
  num_cores: 10
  band: "beta"
  pipeline: "plot"
  merged_fname : merged_flow_pow_subsampFull.csv
  plot_type : 'joint_kde'
  title : 'Directed Connectivity vs. Seizure Involvement'
  subsample : 5000
  random_state : 69420
  y : 'value'
  pre_merged : True
pipeline: 'power'