peri_para:
  stats : 'none'
  num_cores : 20
  buffer : 60
  verbose : False
ei_bal:
  num_cores : 24
power:
  num_cores: 24
  bands : ['delta', 'beta']
plt_flow_power:
  num_cores: 6
  band: "beta"
  pipeline: "merge"
  merged_fname : merged_flow_pow_subsamp5.csv
  plot_type : 'scatter'
  subample : 10
  random_state : 69420
  y : 'value'
  pre_merged : False
pipeline: 'power'